### ISSUE TITLE
an error in busco mode

### ISSUE THREAD

**Issue by wq-ls** [huangnengCSU/minibusco#2]
Dear huangneng,

minibusco is a very good software. But I have some problems doing genome evaluation using busco mode.

1. I installed the software environment using the following command “conda create -n minibusco -c conda-forge -c bioconda minibusco”.

2. Everything outputs fine when using lite mode.

3. When using the busco mode, I encountered an error when processing the 'Target_species' operation in the python script. The error message is as follows：

....
hmmsearch execute command:
 /dellfsqd2/ST_OCEAN/USER/lishuo11/01_soft/mamba/envs/minibusco/bin/hmmsearch
Traceback (most recent call last):
  File "/dellfsqd2/ST_OCEAN/USER/lishuo11/01_soft/mamba/envs/minibusco/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3080, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 4554, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 4562, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Target_species'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/dellfsqd2/ST_OCEAN/USER/lishuo11/01_soft/mamba/envs/minibusco/bin/minibusco", line 10, in <module>
    sys.exit(main())
  File "/dellfsqd2/ST_OCEAN/USER/lishuo11/01_soft/mamba/envs/minibusco/lib/python3.7/site-packages/minibusco.py", line 2512, in main
    args.func(args)
  File "/dellfsqd2/ST_OCEAN/USER/lishuo11/01_soft/mamba/envs/minibusco/lib/python3.7/site-packages/minibusco.py", line 2348, in analyze
    ar.Run()
  File "/dellfsqd2/ST_OCEAN/USER/lishuo11/01_soft/mamba/envs/minibusco/lib/python3.7/site-packages/minibusco.py", line 1234, in Run
    self.Run_busco_mode()
  File "/dellfsqd2/ST_OCEAN/USER/lishuo11/01_soft/mamba/envs/minibusco/lib/python3.7/site-packages/minibusco.py", line 1310, in Run_busco_mode
    filtered_species = records_df["Target_species"].unique()
  File "/dellfsqd2/ST_OCEAN/USER/lishuo11/01_soft/mamba/envs/minibusco/lib/python3.7/site-packages/pandas/core/frame.py", line 3024, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/dellfsqd2/ST_OCEAN/USER/lishuo11/01_soft/mamba/envs/minibusco/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3082, in get_loc
    raise KeyError(key) from err
KeyError: 'Target_species'

Looking forward to some replies from you.

Shuoli

**Comment by huangnengCSU** [comment]
Hi @wq-ls, thanks for your report. Can you help me to check something in the output folder?

    1. Whether there is a successful miniprot output alignment file named "miniprot_output.gff" and what is the file size? (check whether miniprot running successfully)
    2. How many files in the directory of "/hmmer_output/"? (check whether hmmsearch running successfully)
    3. What is the file size of "gene_marker.fasta" and "translated_protein.fasta"?


Best,
Neng

**Comment by wq-ls** [comment]
> 

Hi Neng, thank you very much for your reply.

1. The database I used for testing is actinopterygii_odb10. The miniprot_output.gff file is output successfully and is 98Mb in size. I got the “miniprot.done” file. 

2. There are 3638 files in the directory of "/hmmer_output/". I got the “hmmsearch.done” file.

3. The gene_marker.fasta file is 1.9 Mb.

<img width="493" alt="image" src="https://github.com/huangnengCSU/minibusco/assets/50230939/30bb461b-0d32-4ed7-86c0-768e0a65eb8b">

4. I also tried to use the miniprot_output.gff output in lite mode for "minibusco analyze" analysis, and got the same error.  The command is “minibusco analyze -g miniprot_output.gff -o output2_dir -l actinopterygii -t 10 ”

**Comment by wq-ls** [comment]
> Hi @wq-ls, thanks for your report. Can you help me to check something in the output folder?
> 
> ```
> 1. Whether there is a successful miniprot output alignment file named "miniprot_output.gff" and what is the file size? (check whether miniprot running successfully)
> 2. How many files in the directory of "/hmmer_output/"? (check whether hmmsearch running successfully)
> 3. What is the file size of "gene_marker.fasta" and "translated_protein.fasta"?
> ```
> 
> Best, Neng

Hi Neng, thank you very much for your reply.

1. The database I used for testing is actinopterygii_odb10. The miniprot_output.gff file is output successfully and is 98Mb in size. I got the “miniprot.done” file.

2. There are 3638 files in the directory of "/hmmer_output/". I got the “hmmsearch.done” file.

3. The translated_protein.fasta file is 1.9 Mb. The gene_marker.fasta file was not output in the result directory. 

<img width="493" alt="image" src="https://github.com/huangnengCSU/minibusco/assets/50230939/82486b17-d8b2-457b-ba41-fcfca5f34732">

**Comment by wq-ls** [comment]
Hi Neng,

Sorry, the error reported by the software is due to the problem of my software installation environment. 
I reinstalled the MiniBUSCO software environment, and the busco mode successfully ran through when I tested again.

Last but not least, MiniBUSCO runs really fast!!!

**Comment by henni164** [comment]
> Hi Neng,
> 
> Sorry, the error reported by the software is due to the problem of my software installation environment. I reinstalled the MiniBUSCO software environment, and the busco mode successfully ran through when I tested again.
> 
> Last but not least, MiniBUSCO runs really fast!!!

Sorry, can I ask how you solved this environment issue?
I asked my HPC IT to install this for me but I have run into the same error message as you.
It would be helpful for me to know what the problem was when I ask them to fix the installation. :)

Thanks!

**Comment by Biols0208** [comment]
> > Hi Neng,
> > Sorry, the error reported by the software is due to the problem of my software installation environment. I reinstalled the MiniBUSCO software environment, and the busco mode successfully ran through when I tested again.
> > Last but not least, MiniBUSCO runs really fast!!!
> 
> Sorry, can I ask how you solved this environment issue? I asked my HPC IT to install this for me but I have run into the same error message as you. It would be helpful for me to know what the problem was when I ask them to fix the installation. :)
> 
> Thanks!

Hi henni164,

I have tried 3 installation methods, and only one-click installation using conda to create a new virtual environment can work normally. All needed software and libraries come from the virtual conda environment.

<img width="311" alt="image" src="https://github.com/huangnengCSU/compleasm/assets/50230939/e1fedb3b-55c7-45b4-af8d-62efb42c78ed">

**Comment by henni164** [comment]
> Hi henni164,
> 
> I have tried 3 installation methods, and only one-click installation using conda to create a new virtual environment can work normally. All needed software and libraries come from the virtual conda environment.

Thanks wq-ls!! I will let them know and hopefully they can sort it out.
